### ISSUE TITLE
Implement move items

### ISSUE THREAD

**Issue by jordic** [guillotinaweb/guillotina_react#16]
Copy and move items, could be easy implemented with an small UI abastraction, something like this colud do the work pretty well.

![image](https://user-images.githubusercontent.com/64216/72680038-7c78bb00-3ab5-11ea-8de1-c99f0afcd84f.png)

You can copy items, whenever you are, they are stored on a "clipboard" (localstorage). Later, you can navigate outside, goto the folder you want to move them, and there, you can paste or move.

After paste or move (items are removed from the clipboard)

**Comment by aralroca** [comment]
@jordic I want to propose the next Draft PR (WIP): https://github.com/guillotinaweb/guillotina_react/pull/24

![actions](https://user-images.githubusercontent.com/13313058/73783594-42d1d080-4794-11ea-8a0a-68736b588105.gif)


The idea is that instead of using a modal, we can directly apply the actions on the page using checkboxes to select which items do you want to apply some action.

Right now I just reimplemented the "Delete" to support to remove multiple items at the same time. And "Move" and "Copy" are in progress.
